apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-package
  labels:
    app: python-package-pod
spec:
  selector:
    matchLabels:
      app: python-package-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: python-package-pod
    spec:
      containers:
      - name: python-package-app
        image: docker.io/urishav/first_repo:assignment_1
        imagePullPolicy: Always
        command: ["python3", "out/classes/exercise2.py"]
